language: python

dist: xenial

# Use container-based infrastructure for quicker build start-up
sudo: false

script: docker run -it --rm -v "$PWD:/repo" archlinux/base bash /repo/travis-build.sh

matrix:
    fast_finish: true
